-- AlterTable
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "birth_date" VARCHAR(10);
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "cpf_cnpj" VARCHAR(18);
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "gender" VARCHAR(20);
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "instagram" VARCHAR(100);
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "person_type" VARCHAR(10);
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "photo" TEXT;
ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "whatsapp" VARCHAR(20);
